
sonar.sources=src
sonar.host.url=https://sonarqube.com.br
sonar.exclusions= .vscode/**, dist/**, node_modules/**, commitlint.config.js, reports-test/**, coverage/**, **/__test__/**, src/middlewares/authentication.ts, src/common/filters/**, src/main.ts, src/modules/app.controller.ts, src/modules/app.module.ts, src/config/observability.ts, src/config/date.ts, src/config/documentation.ts, src/config/uuid.ts
sonar.projectName=api-exemplo
sonar.projectKey=projetos_api-exemplo
sonar.projectVersion=1.0
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts,**/*.test.ts.snap
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
